acc_x_test <- read.table("body_acc_x_test.txt")
acc_y_test <- read.table("body_acc_y_test.txt")
acc_z_test <- read.table("body_acc_z_test.txt")
acc_x_train <- read.table("body_acc_x_train.txt")
acc_y_train <- read.table("body_acc_y_train.txt")
acc_z_train <- read.table("body_acc_z_train.txt")
gyro_x_test <- read.table("body_gyro_x_test.txt")
gyro_y_test <- read.table("body_gyro_y_test.txt")
gyro_z_test <- read.table("body_gyro_z_test.txt")
gyro_x_train <- read.table("body_gyro_x_train.txt")
gyro_y_train <- read.table("body_gyro_y_train.txt")
gyro_z_train <- read.table("body_gyro_z_train.txt")
total_acc_x_test <- read.table("total_acc_x_test.txt")
total_acc_y_test <- read.table("total_acc_y_test.txt")
total_acc_z_test <- read.table("total_acc_z_test.txt")
total_acc_x_train <- read.table("total_acc_x_train.txt")
total_acc_y_train <- read.table("total_acc_y_train.txt")
total_acc_z_train <- read.table("total_acc_z_train.txt")

acc_x <- rbind(acc_x_test, acc_x_train)
acc_y <- rbind(acc_y_test, acc_y_train)
acc_z <- rbind(acc_z_test, acc_z_train)
gyro_x <- rbind(gyro_x_test, gyro_y_train)
gyro_y <- rbind(gyro_y_test, gyro_y_train)
gyro_z <- rbind(gyro_z_test, gyro_z_train)
total_acc_x <- rbind(total_acc_x_test, total_acc_x_train)
total_acc_y <- rbind(total_acc_y_test, total_acc_y_train)
total_acc_z <- rbind(total_acc_z_test, total_acc_z_train)


acc_x_df <- data.frame(acc_x)
acc_x_df['Walking_Avg'] <- apply(acc_x, 1, mean)
final_df <- acc_x_df['Walking_Avg']
final_df['Walking_Std'] <- apply(acc_x, 1, sd)
final_df['Walking_Upstairs_Avg'] <- apply(acc_y, 1, mean)
final_df['Walking_Upstairs_Std'] <- apply(acc_y, 1, sd)
final_df['Walking_Downstairs_Avg'] <- apply(acc_z, 1, mean)
final_df['Walking_Downstairs_Std'] <- apply(acc_z, 1, sd)
final_df['Sitting_Avg'] <- apply(gyro_x, 1, mean)
final_df['Sitting_Std'] <- apply(gyro_x, 1, sd)
final_df['Standing_Avg'] <- apply(gyro_y, 1, mean)
final_df['Standing_Std'] <- apply(gyro_y, 1, sd)
final_df['Laying_Avg'] <- apply(gyro_z, 1, mean)
final_df['Laying_Std'] <- apply(gyro_z, 1, sd)
final_df['Total_X_Avg'] <- apply(total_acc_x, 1, mean)
final_df['Total_X_Std'] <- apply(total_acc_x, 1, sd)
final_df['Total_Y_Avg'] <- apply(total_acc_y, 1, mean)
final_df['Total_Y_Std'] <- apply(total_acc_y, 1, sd)
final_df['Total_Z_Avg'] <- apply(total_acc_z, 1, mean)
final_df['Total_Z_Std'] <- apply(total_acc_z, 1, sd)


summary_df <- final_df['Walking_Avg']
summary_df <- sapply(summary_df, mean)
summary_df['Walking_Upstairs_Avg'] <- sapply(final_df['Walking_Upstairs_Avg'], mean)
summary_df['Walking_Downstairs_Avg'] <- sapply(final_df['Walking_Downstairs_Avg'], mean)
summary_df['Sitting_Avg'] <- sapply(final_df['Sitting_Avg'], mean)
summary_df['Standing_Avg'] <- sapply(final_df['Standing_Avg'], mean)
summary_df['Laying_Avg'] <- sapply(final_df['Laying_Avg'], mean)
summary_df['Total_X_Avg'] <- sapply(final_df['Total_X_Avg'], mean)
summary_df['Total_Y_Avg'] <- sapply(final_df['Total_Y_Avg'], mean)
summary_df['Total_Z_Avg'] <- sapply(final_df['Total_Z_Avg'], mean)

write.table(summary_df, file = "final_table.txt", row.names = FALSE)
